# yaml-language-server: $schema=https://github.com/Azure/deployment-environments/releases/download/2022-11-11-preview/manifest.schema.json
name: Container-App-with-Cosmos_AZD-template
version: 1.0.0
summary: Azure Container APP with Cosmos Environment
description: Deploys an Azure Container App with Cosmos, it is compatible with azd.
runner: ARM
templatePath: azuredeploy.json

parameters:
  - id: runtimeType
    name: Runtime Type
    description: 'Runtime Type of the container App runtime,eg python, nodejs or java.'
    type: string
    required: true
    allowed:
      - "python"
      - "nodejs"
      - "java"
  - id: repoUrl
    name: Repository URL
    type: string
    description: Path the the application source code
    allowed:
      - "https://github.com/azure-samples/todo-java-mongo-aca"
      - "https://github.com/azure-samples/todo-nodejs-mongo-aca"
      - "https://github.com/azure-samples/todo-python-mongo-aca"
    
    

